import './styles.css';
import { advanceDay, closeDeal, completeAppointment, completeContact, convertOpportunity, convertToClient, createDeal, createNewGame, activateDeal, enterEscrow, loadGame, negotiateBrokerage, qualifyOpportunity, saveGame, serializeSave, deserializeSave, selectLead } from './core/simulation.js';

let state = loadGame() ?? createNewGame();
let message = 'Starter opportunity ready.';
let screen = new URLSearchParams(window.location.search).has('studio') ? 'studio' : 'dashboard';
let leadQuery = '';
let leadFilter = 'All';

const hours = () => `${Math.floor(state.player.gameHours / 8)}d ${state.player.gameHours % 8}h`;
const action = (label, fn) => `<button data-action="${fn}">${label}</button>`;
const glyphFor = (status) => ['Closed', 'Client', 'Active', 'Completed', 'Won'].includes(status) ? '●' : ['Escrow', 'Appointment Scheduled'].includes(status) ? '◆' : ['Qualified', 'Connected'].includes(status) ? '◑' : '○';
const badge = (status) => `<span class="badge"><span aria-hidden="true">${glyphFor(status)}</span> ${status}</span>`;
const nextStep = () => !state.lead ? ['Review your starter opportunity.', 'opportunities'] : state.lead.status === 'New' ? ['Make first contact with your new lead.', 'leads'] : state.lead.status === 'Connected' ? ['Complete the scheduled appointment.', 'appointments'] : state.lead.status === 'Appointment Scheduled' ? ['Convert the relationship into a client.', 'leads'] : !state.deal ? ['Create a deal for your active client.', 'deals'] : state.deal.status === 'Draft' ? ['Activate the draft deal.', 'deals'] : state.deal.status === 'Active' ? ['Move the active deal into escrow.', 'deals'] : state.deal.status === 'Escrow' ? ['Review the closing conditions.', 'deals'] : ['Review your latest commission and career progress.', 'ledger'];
const journeyCopy = () => !state.lead ? ['Step 1 of 6', 'Review the opportunity and decide whether to qualify it.'] : state.lead.status === 'New' ? ['Step 2 of 6', 'Make a successful first contact and begin building trust.'] : state.lead.status === 'Connected' ? ['Step 3 of 6', 'Complete the appointment and learn whether the relationship is ready.'] : state.lead.status === 'Appointment Scheduled' ? ['Step 4 of 6', 'Convert the qualified relationship into your first client.'] : !state.deal ? ['Step 5 of 6', 'Create a deal for the client and prepare the transaction.'] : state.deal.status !== 'Closed' ? ['Step 5 of 6', 'Progress the transaction toward a successful close.'] : ['Step 6 of 6', 'Your first transaction is complete. Review the ledger and continue your career.'];
const navItems = [['setup', 'New Game'], ['dashboard', 'Dashboard'], ['opportunities', 'Opportunities'], ['leads', 'Leads'], ['appointments', 'Appointments & Tasks'], ['clients', 'Clients'], ['deals', 'Deals'], ['ledger', 'Financial Ledger'], ['activity', 'Activity & Notifications'], ['save', 'Save / Load'], ['studio', 'Simulator Studio']];

function screenContent() {
  if (screen === 'studio') return `<section class="studio-page"><div class="studio-hero"><p class="eyebrow">DEVELOPER WORKSPACE</p><h2>Simulator Studio</h2><p>See what exists, what is approved, and what could come next—before changing the player experience.</p><span class="badge">First Playable · review mode</span></div><div class="studio-grid"><article class="card studio-panel"><p class="eyebrow">SYSTEM MAP</p><h3>Current career loop</h3><div class="system-flow"><span>Opportunity</span><i aria-hidden="true">→</i><span>Lead</span><i aria-hidden="true">→</i><span>Client</span><i aria-hidden="true">→</i><span>Deal</span><i aria-hidden="true">→</i><span>Close</span></div><p class="note">Core rules live in <span class="mono">src/core/</span>; screens dispatch commands from the UI layer.</p></article><article class="card studio-panel"><p class="eyebrow">RELEASE HEALTH</p><h3>First Playable gates</h3><div class="gate-list"><div><span>Automated tests</span><strong class="gate-good">10 passing</strong></div><div><span>Production build</span><strong class="gate-good">Passing</strong></div><div><span>Persistence fixture</span><strong class="gate-good">Verified</strong></div><div><span>Browser, mobile, SR review</span><strong class="gate-open">Open</strong></div></div></article><article class="card studio-panel"><p class="eyebrow">SHIPPED SYSTEMS</p><h3>What is already built</h3><div class="tag-list"><span>Save / load</span><span>Checksums</span><span>Recovery saves</span><span>Contact methods</span><span>Guided consultation</span><span>Ledger reconciliation</span><span>Responsive navigation</span><span>Keyboard focus</span></div></article><article class="card studio-panel"><p class="eyebrow">NEXT IDEAS</p><h3>Candidate feature queue</h3><div class="idea-list"><div><span><strong>Interactive smoke harness</strong><small>Automate the approved end-to-end journey</small></span><b class="idea-safe">High value · in scope</b></div><div><span><strong>Feature impact map</strong><small>Show which screens, rules, and tests a proposal touches</small></span><b class="idea-safe">High value · tooling</b></div><div><span><strong>Properties and showings</strong><small>Expand beyond the current First Playable loop</small></span><b class="idea-deferred">Deferred · approval needed</b></div></div></article></div><div class="studio-footer"><strong>Guardrail:</strong> new gameplay meaning, formulas, lifecycle rules, or scope require an approved decision before implementation.</div></section>`;
  if (screen === 'setup') return `<section class="card page"><p class="eyebrow">CAREER SETUP</p><h2>Start a new career</h2><p>Choose a display name for your realtor career. The starter scenario will begin with a new opportunity and a clean local save state.</p><form id="new-game-form" class="form"><label for="display-name">Display name</label><input id="display-name" name="displayName" maxlength="40" minlength="2" value="${state.player.displayName}" required /><p class="note">Your game is single-player and saved locally in this browser.</p><button type="submit">Start new game</button></form></section>`;
  if (screen === 'dashboard') return `<section class="grid">
    <article class="card hero"><p class="eyebrow">CAREER DASHBOARD</p><h2>${state.player.displayName}</h2><p class="note">Starter scenario · ${hours()} elapsed</p><div class="metrics"><span><b>${state.player.trust}</b>Trust<div class="progress"><i style="width:${state.player.trust}%"></i></div></span><span><b>${state.player.reputation}</b>Reputation<div class="progress"><i style="width:${state.player.reputation}%"></i></div></span><span><b>${state.lead?.score ?? '—'}</b>Lead score</span><span><b>$${(state.player.cashBalance ?? 0).toLocaleString()}</b>Cash</span></div><div class="pipeline" aria-label="Career pipeline">${['Opportunity', 'Lead', 'Appointment', 'Client', 'Deal', 'Closed'].map((stage, index) => `<span class="pipeline-step ${index === 0 ? 'current' : ''}"><i aria-hidden="true">${index === 0 ? '◉' : '○'}</i>${stage}</span>`).join('')}</div></article>
    <article class="card"><p class="eyebrow">TODAY’S PRIORITY</p><h3>Next recommended action</h3><p>${nextStep()[0]}</p><button data-screen="${nextStep()[1]}">Open workspace</button></article>
    <article class="card"><p class="eyebrow">FIRST-DAY JOURNEY</p><h3>${journeyCopy()[0]}</h3><p>${journeyCopy()[1]}</p><p class="note">The goal is to build one relationship, complete one transaction, and understand why each action matters.</p></article>
    <article class="card"><p class="eyebrow">CAREER STATUS</p><h3>Brokerage contract</h3><p>Player share: <strong>${Math.round(state.player.brokerageContract.playerShare * 100)}%</strong></p><p class="note">One-time negotiation ${state.player.brokerageContract.negotiated ? 'complete' : 'available'}.</p></article>
  </section>`;
  if (screen === 'opportunities') return `<section class="card page"><p class="eyebrow">OPPORTUNITIES</p><h2>Opportunity Inbox</h2><p>Review potential business and move qualified opportunities into your CRM.</p><button class="opportunity-card" data-screen="opportunity-detail"><span><strong>${state.opportunity.type} opportunity</strong><small>Source: ${state.opportunity.source}</small></span>${badge(state.opportunity.status)}</button><p class="note">Select the opportunity to review its details and available lifecycle actions.</p></section>`;
  if (screen === 'opportunity-detail') return `<section class="card page"><p class="eyebrow">OPPORTUNITY DETAIL</p><h2>${state.opportunity.type} opportunity</h2><div class="detail-grid"><div><span class="label">Status</span><strong>${state.opportunity.status}</strong></div><div><span class="label">Source</span><strong>${state.opportunity.source}</strong></div><div><span class="label">Record ID</span><strong class="mono">${state.opportunity.id}</strong></div></div><p>Lifecycle actions are validated by the opportunity engine and recorded in activity history.</p><div class="actions">${state.opportunity.status === 'Discovered' ? action('Qualify opportunity', 'qualify') : ''}${state.opportunity.status === 'Qualified' ? action('Win opportunity', 'convert') : ''}${state.opportunity.convertedLeadId ? '<button data-screen="leads">Open linked lead</button>' : ''}<button class="secondary" data-screen="opportunities">Back to inbox</button></div></section>`;
  if (screen === 'leads') { const leads = (state.leads ?? []).filter((lead) => (leadFilter === 'All' || lead.type === leadFilter || lead.status === leadFilter) && `${lead.firstName} ${lead.lastName} ${lead.motivation}`.toLowerCase().includes(leadQuery.toLowerCase())); return `<section class="card page"><p class="eyebrow">CRM WORKSPACE</p><h2>Lead inbox</h2><div class="crm-tools"><input id="lead-search" class="crm-search" type="search" placeholder="Search leads or goals" value="${leadQuery}" aria-label="Search leads or goals" /><select id="lead-filter" aria-label="Filter leads"><option ${leadFilter === 'All' ? 'selected' : ''}>All</option><option ${leadFilter === 'Buyer' ? 'selected' : ''}>Buyer</option><option ${leadFilter === 'Seller' ? 'selected' : ''}>Seller</option><option ${leadFilter === 'Investor' ? 'selected' : ''}>Investor</option><option ${leadFilter === 'New' ? 'selected' : ''}>New</option><option ${leadFilter === 'Connected' ? 'selected' : ''}>Connected</option><option ${leadFilter === 'Client' ? 'selected' : ''}>Client</option></select></div>${leads.length ? leads.map((lead) => `<button class="opportunity-card lead-row" data-lead-id="${lead.id}"><span><strong>${lead.firstName} ${lead.lastName}</strong><small>${lead.type} · ${lead.motivation}</small></span><span><span class="badge">${lead.status}</span><small>Trust ${lead.trust} · Score ${lead.score}</small></span></button>`).join('') : '<p class="note">No leads match this view.</p>'}<p class="note">${leads.length} lead${leads.length === 1 ? '' : 's'} in view.</p></section>`; }
  if (screen === 'lead-detail') return `<section class="card page"><p class="eyebrow">LEAD DETAIL</p><h2>${state.lead?.firstName ?? 'Starter'} ${state.lead?.lastName ?? 'lead'}</h2><p class="note">${state.lead?.type ?? 'Prospect'} · ${state.lead?.motivation ?? 'New opportunity'}</p><div class="detail-grid"><div><span class="label">Lifecycle status</span><strong>${state.lead?.status ?? 'Unavailable'}</strong></div><div><span class="label">Trust</span><strong>${state.lead?.trust ?? '—'} / 100</strong></div><div><span class="label">Lead score</span><strong>${state.lead?.score ?? '—'} / 100</strong></div><div><span class="label">Budget</span><strong>${state.lead?.budgetRange ?? '—'}</strong></div><div><span class="label">Timeline</span><strong>${state.lead?.timeline ?? '—'}</strong></div><div><span class="label">Contact</span><strong>${state.lead?.preferredContact ?? '—'}</strong></div></div><div class="callout"><strong>Client concern</strong><p>${state.lead?.concern ?? 'No concern recorded yet.'}</p></div><h3>Contact action</h3><p>Choose an approach. Successful contact advances the lead by two hours and adds three trust points.</p><div class="actions">${state.lead?.status === 'New' ? '<button data-action="contact-phone">Phone call</button><button data-action="contact-text">Text message</button><button data-action="contact-email">Email</button>' : ''}${state.lead?.status === 'Connected' ? action('Complete appointment', 'appointment') : ''}${state.lead?.status === 'Appointment Scheduled' ? action('Convert to client', 'client') : ''}<button class="secondary" data-screen="leads">Back to CRM</button></div><h3 class="subheading">Relationship activity</h3>${state.lead?.activity?.length ? state.lead.activity.slice().reverse().map((item) => `<div class="entity-row"><span><strong>${item.type}</strong><small>Day ${item.dayIndex} · ${item.message}</small></span><span class="note">${item.gameHours}h</span></div>`).join('') : '<p class="note">No lead-specific activity recorded yet.</p>'}</section>`;
  if (screen === 'appointments') return `<section class="card page"><p class="eyebrow">SCHEDULE</p><h2>Appointments & Tasks</h2>${state.lead?.status === 'Connected' ? `<div class="entity-row"><span><strong>Consultation with ${state.lead.firstName} ${state.lead.lastName}</strong><small>Ready to complete · ${state.lead.preferredContact} follow-up</small></span>${badge('Appointment Scheduled')}</div><div class="callout"><strong>Consultation goals</strong><p>Understand the client’s ${state.lead.motivation.toLowerCase()}, confirm the ${state.lead.budgetRange} budget, and discuss the ${state.lead.timeline.toLowerCase()} timeline.</p></div><div class="actions">${action('Complete appointment', 'appointment')}</div>` : state.lead?.status === 'Appointment Scheduled' || state.client ? `<div class="entity-row"><span><strong>Consultation completed with ${state.lead?.firstName ?? 'starter lead'}</strong><small>Trust impact recorded · next step is client conversion</small></span>${badge('Completed')}</div>` : '<p class="note">No appointments or tasks yet. Complete a successful lead contact to schedule one.</p>'}</section>`;
  if (screen === 'clients') return `<section class="card page"><p class="eyebrow">CLIENTS</p><h2>Client Portfolio</h2>${state.client ? `<button class="opportunity-card" data-screen="client-detail"><span><strong>Starter client</strong><small>Relationship trust: ${state.client.trust}</small></span><span class="badge">${state.client.status}</span></button>` : '<p class="note">No clients yet. Complete the lead milestones to create one.</p>'}</section>`;
  if (screen === 'client-detail') return `<section class="card page"><p class="eyebrow">CLIENT DETAIL</p><h2>${state.lead?.firstName ?? 'Starter'} ${state.lead?.lastName ?? 'client'}</h2><div class="callout"><strong>Relationship established</strong><p>You completed the first relationship milestones. The next step is to create a transaction that serves the client’s goal.</p></div><div class="detail-grid"><div><span class="label">Status</span><strong>${state.client?.status ?? 'Unavailable'}</strong></div><div><span class="label">Relationship trust</span><strong>${state.client?.trust ?? '—'} / 100</strong></div><div><span class="label">Motivation</span><strong>${state.lead?.motivation ?? '—'}</strong></div></div><p>Client records connect the relationship to the transaction workspace.</p><div class="actions"><button data-screen="deals">Open deal workspace</button><button class="secondary" data-screen="clients">Back to clients</button></div></section>`;
  if (screen === 'deals') return `<section class="card page"><p class="eyebrow">TRANSACTIONS</p><h2>Deal Workspace</h2>${state.deal ? `<div class="entity-row"><strong>Starter residential deal</strong><span class="badge">${state.deal.status}</span></div><div class="detail-grid"><div><span class="label">Purchase price</span><strong>$${state.deal.purchasePrice.toLocaleString()}</strong></div><div><span class="label">Commission rate</span><strong>3%</strong></div><div><span class="label">Player share</span><strong>${Math.round(state.deal.playerShare * 100)}%</strong></div></div><div class="actions">${state.deal.status === 'Draft' ? action('Activate deal', 'activate') : ''}${state.deal.status === 'Active' ? action('Enter escrow', 'escrow') : ''}${state.deal.status === 'Escrow' ? '<button data-screen="close-confirmation">Review closing</button>' : ''}</div>` : `${state.client ? `<div class="actions">${action('Create deal', 'deal')}</div>` : '<div class="actions"><button disabled title="Convert the lead into a client first">Create deal</button></div><p class="note">Create deal is unavailable until the lead becomes an active client.</p>'}`}</section>`;
  if (screen === 'close-confirmation') return `<section class="card page"><p class="eyebrow">CLOSING CONFIRMATION</p><h2>Review before closing</h2><p>Closing this escrow deal will create one immutable commission ledger entry and move the client to Past Client.</p><div class="detail-grid"><div><span class="label">Gross commission</span><strong>$${(state.deal.purchasePrice * state.deal.commissionRate).toFixed(2)}</strong></div><div><span class="label">Player net</span><strong>$${(state.deal.purchasePrice * state.deal.commissionRate * state.deal.playerShare).toFixed(2)}</strong></div><div><span class="label">Posting</span><strong>Immediate</strong></div></div><div class="actions"><button data-action="close">Confirm close</button><button class="secondary" data-screen="deals">Return to deal</button></div></section>`;
  if (screen === 'ledger') { const gross = state.ledger.reduce((sum, entry) => sum + (entry.grossCommission ?? 0), 0); const net = state.ledger.reduce((sum, entry) => sum + entry.amount, 0); const brokerage = state.ledger.reduce((sum, entry) => sum + (entry.brokerageShare ?? 0), 0); return `<section class="card page"><p class="eyebrow">FINANCE</p><h2>Financial Ledger</h2><div class="metrics"><span><b>$${gross.toFixed(2)}</b>Gross</span><span><b>$${brokerage.toFixed(2)}</b>Brokerage</span><span><b>$${net.toFixed(2)}</b>Player net</span></div>${state.ledger.length ? state.ledger.map((entry) => `<div class="entity-row"><span><strong>${entry.type}</strong><small>${entry.description}</small></span><span>$${entry.amount.toFixed(2)} ${entry.currency}</span></div>`).join('') : '<p class="note">No financial transactions yet. A successful close will post commission here.</p>'}<p class="note">Reconciliation: cash earnings equal the sum of player net ledger postings.</p></section>`; }
  if (screen === 'activity') return `<section class="card page"><p class="eyebrow">HISTORY</p><h2>Activity & Notifications</h2>${state.activities.length ? state.activities.slice().reverse().map((item) => `<div class="entity-row"><span>${item.message}</span><span class="note">${item.gameHours}h</span></div>`).join('') : '<p class="note">No activity recorded yet.</p>'}<h3 class="subheading">Notifications</h3>${state.notifications.map((item) => `<div class="entity-row"><span>${item.message}</span><span class="badge">${item.read ? 'Read' : 'New'}</span></div>`).join('')}</section>`;
  const hasSave = Boolean(loadGame());
  return `<section class="card page"><p class="eyebrow">PERSISTENCE</p><h2>Save / Load</h2><p>Saves are stored locally in this browser. Export a backup before clearing browser data or changing devices.</p><div class="detail-grid"><div><span class="label">Save state</span><strong>${hasSave ? 'Available' : 'Not created'}</strong></div><div><span class="label">Entities</span><strong>${[state.opportunity, state.lead, state.client, state.deal].filter(Boolean).length}</strong></div><div><span class="label">Ledger entries</span><strong>${state.ledger.length}</strong></div></div><div class="actions">${action('Save game', 'save')}<button data-action="load" ${hasSave ? '' : 'disabled'} title="${hasSave ? 'Load the saved career' : 'Save the game before loading it'}">Load game</button>${action('Export backup', 'export')}<button data-action="import">Import backup</button><input id="save-file" type="file" accept="application/json,.json" hidden /></div><p class="note">${message}</p></section>`;
}

function render() {
  document.querySelector('#app').innerHTML = `
    <section class="shell" aria-labelledby="game-title">
      <header class="topbar"><div class="brand"><img src="/real-estate-simulator/assets/realtor-sim-logo.svg" alt="Realtor Sim" /><div><p class="eyebrow">CAREER SIMULATION</p><h1 id="game-title">New Realtor Simulator</h1></div></div><div class="topbar-actions"><span class="status">Day ${state.player.dayIndex ?? 0}</span><button data-action="advance">Advance day</button></div></header>
      <nav class="nav" aria-label="Primary navigation">${navItems.map(([key, label]) => `<button type="button" class="nav-button ${screen === key ? 'active' : ''}" aria-current="${screen === key ? 'page' : 'false'}" data-screen="${key}">${label}</button>`).join('')}</nav>
      <main id="main-content" tabindex="-1">${screenContent()}</main>
      <section class="card feedback" role="status" aria-live="polite"><strong>${message}</strong></section>
    </section>`;
  document.querySelectorAll('[data-screen]').forEach((button) => button.addEventListener('click', () => { screen = button.dataset.screen; render(); }));
  document.querySelectorAll('[data-lead-id]').forEach((button) => button.addEventListener('click', () => { try { state = selectLead(state, button.dataset.leadId); screen = 'lead-detail'; render(); } catch (error) { message = error.message; render(); } }));
  document.querySelector('#lead-search')?.addEventListener('input', (event) => { leadQuery = event.target.value; render(); document.querySelector('#lead-search')?.focus(); });
  document.querySelector('#lead-filter')?.addEventListener('change', (event) => { leadFilter = event.target.value; render(); });
  document.querySelectorAll('[data-action]').forEach((button) => button.addEventListener('click', () => run(button.dataset.action)));
  document.querySelector('#save-file')?.addEventListener('change', (event) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { state = deserializeSave(String(reader.result)); saveGame(state); message = 'Backup imported and saved locally.'; screen = 'dashboard'; render(); } catch (error) { message = error.message; render(); } }; reader.readAsText(file); });
  document.querySelector('#new-game-form')?.addEventListener('submit', (event) => { event.preventDefault(); const displayName = new FormData(event.currentTarget).get('displayName').trim(); if (displayName.length < 2) { message = 'Display name must be at least 2 characters.'; render(); return; } state = createNewGame(displayName); saveGame(state); screen = 'dashboard'; message = 'New career started and saved locally.'; render(); });
  document.querySelector('#main-content')?.focus({ preventScroll: true });
}

function run(name) {
  try {
    const operations = { advance: advanceDay, qualify: qualifyOpportunity, convert: convertOpportunity, contact: completeContact, appointment: completeAppointment, client: convertToClient, deal: createDeal, activate: activateDeal, escrow: enterEscrow, close: closeDeal };
    if (name === 'save') { saveGame(state); message = 'Game saved locally in this browser.'; }
    else if (name === 'load') { state = loadGame() ?? state; message = 'Saved game loaded.'; }
    else if (name === 'contact-phone' || name === 'contact-text' || name === 'contact-email') { const method = name === 'contact-phone' ? 'Phone' : name === 'contact-text' ? 'Text' : 'Email'; state = completeContact(state, method); message = `${method} contact completed successfully.`; }
    else if (name === 'export') { const blob = new Blob([serializeSave(state)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'new-realtor-simulator-save.json'; link.click(); URL.revokeObjectURL(url); message = 'Save backup exported.'; }
    else if (name === 'import') { document.querySelector('#save-file')?.click(); return; }
    else if (name === 'negotiate') { const requested = window.prompt('Choose your player share (50-90):', String(Math.round(state.player.brokerageContract.playerShare * 100))); state = negotiateBrokerage(state, Number(requested) / 100); message = 'Brokerage contract negotiated.'; }
    else { state = operations[name](state); message = name === 'advance' ? `Advanced to day ${state.player.dayIndex}.` : name === 'client' ? 'Client relationship established. Your next objective is to create a deal.' : name === 'close' ? 'First transaction complete. Commission posted and career progress updated.' : `${name} completed successfully.`; if (name === 'close') screen = 'ledger'; }
  } catch (error) { message = error.message; }
  render();
}

render();
