import './styles.css';
import { closeDeal, completeAppointment, completeContact, convertOpportunity, convertToClient, createDeal, createNewGame, activateDeal, enterEscrow, loadGame, negotiateBrokerage, qualifyOpportunity, saveGame } from './core/simulation.js';

let state = loadGame() ?? createNewGame();
let message = 'Starter opportunity ready.';
let screen = 'dashboard';

const hours = () => `${Math.floor(state.player.gameHours / 8)}d ${state.player.gameHours % 8}h`;
const action = (label, fn) => `<button data-action="${fn}">${label}</button>`;
const navItems = [['setup', 'New Game'], ['dashboard', 'Dashboard'], ['opportunities', 'Opportunities'], ['leads', 'Leads'], ['appointments', 'Appointments & Tasks'], ['clients', 'Clients'], ['deals', 'Deals'], ['ledger', 'Financial Ledger'], ['activity', 'Activity & Notifications'], ['save', 'Save / Load']];

function screenContent() {
  if (screen === 'setup') return `<section class="card page"><p class="eyebrow">CAREER SETUP</p><h2>Start a new career</h2><p>Choose a display name for your realtor career. The starter scenario will begin with a new opportunity and a clean local save state.</p><form id="new-game-form" class="form"><label for="display-name">Display name</label><input id="display-name" name="displayName" maxlength="40" minlength="2" value="${state.player.displayName}" required /><p class="note">Your game is single-player and saved locally in this browser.</p><button type="submit">Start new game</button></form></section>`;
  if (screen === 'dashboard') return `<section class="grid">
    <article class="card hero"><p class="eyebrow">CAREER DASHBOARD</p><h2>${state.player.displayName}</h2><p class="note">Starter scenario · ${hours()} elapsed</p><div class="metrics"><span><b>${state.player.trust}</b>Trust</span><span><b>${state.player.reputation}</b>Reputation</span><span><b>${state.lead?.score ?? '—'}</b>Lead score</span><span><b>$${(state.player.cashBalance ?? 0).toLocaleString()}</b>Cash</span></div></article>
    <article class="card"><p class="eyebrow">TODAY</p><h3>Next recommended action</h3><p>${state.lead ? `Continue the lead: ${state.lead.status}.` : 'Review and qualify your starter opportunity.'}</p><button data-screen="${state.lead ? 'leads' : 'opportunities'}">Open workspace</button></article>
    <article class="card"><p class="eyebrow">CAREER STATUS</p><h3>Brokerage contract</h3><p>Player share: <strong>${Math.round(state.player.brokerageContract.playerShare * 100)}%</strong></p><p class="note">One-time negotiation ${state.player.brokerageContract.negotiated ? 'complete' : 'available'}.</p></article>
  </section>`;
  if (screen === 'opportunities') return `<section class="card page"><p class="eyebrow">OPPORTUNITIES</p><h2>Opportunity Inbox</h2><p>Review potential business and move qualified opportunities into your CRM.</p><button class="opportunity-card" data-screen="opportunity-detail"><span><strong>${state.opportunity.type} opportunity</strong><small>Source: ${state.opportunity.source}</small></span><span class="badge">${state.opportunity.status}</span></button><p class="note">Select the opportunity to review its details and available lifecycle actions.</p></section>`;
  if (screen === 'opportunity-detail') return `<section class="card page"><p class="eyebrow">OPPORTUNITY DETAIL</p><h2>${state.opportunity.type} opportunity</h2><div class="detail-grid"><div><span class="label">Status</span><strong>${state.opportunity.status}</strong></div><div><span class="label">Source</span><strong>${state.opportunity.source}</strong></div><div><span class="label">Record ID</span><strong class="mono">${state.opportunity.id}</strong></div></div><p>Lifecycle actions are validated by the opportunity engine and recorded in activity history.</p><div class="actions">${state.opportunity.status === 'Discovered' ? action('Qualify opportunity', 'qualify') : ''}${state.opportunity.status === 'Qualified' ? action('Win opportunity', 'convert') : ''}${state.opportunity.convertedLeadId ? '<button data-screen="leads">Open linked lead</button>' : ''}<button class="secondary" data-screen="opportunities">Back to inbox</button></div></section>`;
  if (screen === 'leads') return `<section class="card page"><p class="eyebrow">CRM</p><h2>Lead CRM</h2>${state.lead ? `<button class="opportunity-card" data-screen="lead-detail"><span><strong>Starter lead</strong><small>Trust ${state.lead.trust} · Score ${state.lead.score}</small></span><span class="badge">${state.lead.status}</span></button><p class="note">Open the lead record to review contact actions and progression requirements.</p>` : '<p class="note">No leads yet. Win an opportunity to create your first lead.</p>'}</section>`;
  if (screen === 'lead-detail') return `<section class="card page"><p class="eyebrow">LEAD DETAIL</p><h2>Starter lead</h2><div class="detail-grid"><div><span class="label">Lifecycle status</span><strong>${state.lead?.status ?? 'Unavailable'}</strong></div><div><span class="label">Trust</span><strong>${state.lead?.trust ?? '—'} / 100</strong></div><div><span class="label">Lead score</span><strong>${state.lead?.score ?? '—'} / 100</strong></div></div><h3>Contact action</h3><p>Successful contact advances the lead and consumes the approved action time.</p><div class="actions">${state.lead?.status === 'New' ? action('Log successful contact', 'contact') : ''}${state.lead?.status === 'Connected' ? action('Complete appointment', 'appointment') : ''}${state.lead?.status === 'Appointment Scheduled' ? action('Convert to client', 'client') : ''}<button class="secondary" data-screen="leads">Back to CRM</button></div></section>`;
  if (screen === 'appointments') return `<section class="card page"><p class="eyebrow">SCHEDULE</p><h2>Appointments & Tasks</h2>${state.lead?.status === 'Connected' ? `<div class="entity-row"><span><strong>Starter lead appointment</strong><small>Ready to complete</small></span><span class="badge">Scheduled</span></div><div class="actions">${action('Complete appointment', 'appointment')}</div>` : state.lead?.status === 'Appointment Scheduled' || state.client ? '<div class="entity-row"><span><strong>Starter lead appointment</strong><small>Trust impact recorded</small></span><span class="badge">Completed</span></div>' : '<p class="note">No appointments or tasks yet. Complete a successful lead contact to schedule one.</p>'}</section>`;
  if (screen === 'clients') return `<section class="card page"><p class="eyebrow">CLIENTS</p><h2>Client Portfolio</h2>${state.client ? `<button class="opportunity-card" data-screen="client-detail"><span><strong>Starter client</strong><small>Relationship trust: ${state.client.trust}</small></span><span class="badge">${state.client.status}</span></button>` : '<p class="note">No clients yet. Complete the lead milestones to create one.</p>'}</section>`;
  if (screen === 'client-detail') return `<section class="card page"><p class="eyebrow">CLIENT DETAIL</p><h2>Starter client</h2><div class="detail-grid"><div><span class="label">Status</span><strong>${state.client?.status ?? 'Unavailable'}</strong></div><div><span class="label">Relationship trust</span><strong>${state.client?.trust ?? '—'} / 100</strong></div><div><span class="label">Origin</span><strong>Starter lead</strong></div></div><p>Client records connect the CRM relationship to the transaction workspace.</p><div class="actions"><button data-screen="deals">Open deal workspace</button><button class="secondary" data-screen="clients">Back to clients</button></div></section>`;
  if (screen === 'deals') return `<section class="card page"><p class="eyebrow">TRANSACTIONS</p><h2>Deal Workspace</h2>${state.deal ? `<div class="entity-row"><strong>Starter residential deal</strong><span class="badge">${state.deal.status}</span></div><div class="detail-grid"><div><span class="label">Purchase price</span><strong>$${state.deal.purchasePrice.toLocaleString()}</strong></div><div><span class="label">Commission rate</span><strong>3%</strong></div><div><span class="label">Player share</span><strong>${Math.round(state.deal.playerShare * 100)}%</strong></div></div><div class="actions">${state.deal.status === 'Draft' ? action('Activate deal', 'activate') : ''}${state.deal.status === 'Active' ? action('Enter escrow', 'escrow') : ''}${state.deal.status === 'Escrow' ? '<button data-screen="close-confirmation">Review closing</button>' : ''}</div>` : `${state.client ? `<div class="actions">${action('Create deal', 'deal')}</div>` : '<p class="note">No deal yet. Convert a lead into a client first.</p>'}`}</section>`;
  if (screen === 'close-confirmation') return `<section class="card page"><p class="eyebrow">CLOSING CONFIRMATION</p><h2>Review before closing</h2><p>Closing this escrow deal will create one immutable commission ledger entry and move the client to Past Client.</p><div class="detail-grid"><div><span class="label">Gross commission</span><strong>$${(state.deal.purchasePrice * state.deal.commissionRate).toFixed(2)}</strong></div><div><span class="label">Player net</span><strong>$${(state.deal.purchasePrice * state.deal.commissionRate * state.deal.playerShare).toFixed(2)}</strong></div><div><span class="label">Posting</span><strong>Immediate</strong></div></div><div class="actions"><button data-action="close">Confirm close</button><button class="secondary" data-screen="deals">Return to deal</button></div></section>`;
  if (screen === 'ledger') return `<section class="card page"><p class="eyebrow">FINANCE</p><h2>Financial Ledger</h2>${state.ledger.length ? state.ledger.map((entry) => `<div class="entity-row"><strong>${entry.type}</strong><span>$${entry.amount.toFixed(2)} ${entry.currency}</span></div>`).join('') : '<p class="note">No financial transactions yet. A successful close will post commission here.</p>'}</section>`;
  if (screen === 'activity') return `<section class="card page"><p class="eyebrow">HISTORY</p><h2>Activity & Notifications</h2>${state.activities.length ? state.activities.slice().reverse().map((item) => `<div class="entity-row"><span>${item.message}</span><span class="note">${item.gameHours}h</span></div>`).join('') : '<p class="note">No activity recorded yet.</p>'}<h3 class="subheading">Notifications</h3>${state.notifications.map((item) => `<div class="entity-row"><span>${item.message}</span><span class="badge">${item.read ? 'Read' : 'New'}</span></div>`).join('')}</section>`;
  return `<section class="card page"><p class="eyebrow">PERSISTENCE</p><h2>Save / Load</h2><p>Saves are stored locally in this browser.</p><div class="actions">${action('Save game', 'save')} ${action('Load game', 'load')}</div><p class="note">${message}</p></section>`;
}

function render() {
  document.querySelector('#app').innerHTML = `
    <section class="shell" aria-labelledby="game-title">
      <header class="topbar"><div><p class="eyebrow">CAREER SIMULATION</p><h1 id="game-title">New Realtor Simulator</h1></div><span class="status">First Playable</span></header>
      <nav class="nav" aria-label="Primary navigation">${navItems.map(([key, label]) => `<button class="nav-button ${screen === key ? 'active' : ''}" data-screen="${key}">${label}</button>`).join('')}</nav>
      <main>${screenContent()}</main>
      <section class="card feedback" role="status"><strong>${message}</strong></section>
    </section>`;
  document.querySelectorAll('[data-screen]').forEach((button) => button.addEventListener('click', () => { screen = button.dataset.screen; render(); }));
  document.querySelectorAll('[data-action]').forEach((button) => button.addEventListener('click', () => run(button.dataset.action)));
  document.querySelector('#new-game-form')?.addEventListener('submit', (event) => { event.preventDefault(); const displayName = new FormData(event.currentTarget).get('displayName').trim(); if (displayName.length < 2) { message = 'Display name must be at least 2 characters.'; render(); return; } state = createNewGame(displayName); saveGame(state); screen = 'dashboard'; message = 'New career started and saved locally.'; render(); });
}

function run(name) {
  try {
    const operations = { qualify: qualifyOpportunity, convert: convertOpportunity, contact: completeContact, appointment: completeAppointment, client: convertToClient, deal: createDeal, activate: activateDeal, escrow: enterEscrow, close: closeDeal };
    if (name === 'save') { saveGame(state); message = 'Game saved locally in this browser.'; }
    else if (name === 'load') { state = loadGame() ?? state; message = 'Saved game loaded.'; }
    else if (name === 'negotiate') { const requested = window.prompt('Choose your player share (50-90):', String(Math.round(state.player.brokerageContract.playerShare * 100))); state = negotiateBrokerage(state, Number(requested) / 100); message = 'Brokerage contract negotiated.'; }
    else { state = operations[name](state); message = `${name} completed successfully.`; if (name === 'close') screen = 'ledger'; }
  } catch (error) { message = error.message; }
  render();
}

render();
